#!/bin/sh

export GTK_THEME=Adwaita:dark
export GDK_THEME=Adwaita:dark
export GTK2_RC_FILES=/usr/share/themes/Adwaita/gtk-2.0/gtkrc

export _JAVA_OPTIONS="-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"

/usr/bin/flexibee "$@"
